//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace financesFlow.Exception {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceErrorMessages() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("financesFlow.Exception.ResourceErrorMessages", typeof(ResourceErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A data não pode ultrapassar o limite do dia atual!.
        /// </summary>
        public static string DATA_INCORRETA_OU_MAIOR {
            get {
                return ResourceManager.GetString("DATA_INCORRETA_OU_MAIOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Despesa não encontrada na base de dados..
        /// </summary>
        public static string DESPESA_NAO_ENCONTRADA {
            get {
                return ResourceManager.GetString("DESPESA_NAO_ENCONTRADA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a E-mail ou Senha Invalidos, por favor digite os dados corretos..
        /// </summary>
        public static string EMAIL_OU_SENHA_INVALIDOS {
            get {
                return ResourceManager.GetString("EMAIL_OU_SENHA_INVALIDOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Metodo de pagamento não encontrado!.
        /// </summary>
        public static string METODO_PAGAMENTO_INEXISTENTE {
            get {
                return ResourceManager.GetString("METODO_PAGAMENTO_INEXISTENTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O nome não pode ser vazio!.
        /// </summary>
        public static string NOME_VAZIO {
            get {
                return ResourceManager.GetString("NOME_VAZIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro Desconhecido.
        /// </summary>
        public static string UNKNOWN_ERROR {
            get {
                return ResourceManager.GetString("UNKNOWN_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O e-mail digitado é inválido.
        /// </summary>
        public static string USUARIO_COM_EMAIL_INVALIDO {
            get {
                return ResourceManager.GetString("USUARIO_COM_EMAIL_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O e-mail digitado já esta registrado em base, por favor, digite um e-mail diferente.
        /// </summary>
        public static string USUARIO_COM_EMAIL_JA_EXISTENTE {
            get {
                return ResourceManager.GetString("USUARIO_COM_EMAIL_JA_EXISTENTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O e-mail precisa ser preenchido.
        /// </summary>
        public static string USUARIO_COM_EMAIL_VAZIO {
            get {
                return ResourceManager.GetString("USUARIO_COM_EMAIL_VAZIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O nome precisa ser preenchido.
        /// </summary>
        public static string USUARIO_COM_NOME_VAZIO {
            get {
                return ResourceManager.GetString("USUARIO_COM_NOME_VAZIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A senha precisa ser prenchida corretamente.
        /// </summary>
        public static string USUARIO_COM_SENHA_EM_BRANCO {
            get {
                return ResourceManager.GetString("USUARIO_COM_SENHA_EM_BRANCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A sua senha recisa conter no minímo 8 caracteres, contendo pelo menos uma letra maiúscula uma letra minúscula, um número e um caractere especial (! ? * #)..
        /// </summary>
        public static string USUARIO_COM_SENHA_INVALIDA {
            get {
                return ResourceManager.GetString("USUARIO_COM_SENHA_INVALIDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O valor não pode ser igual a zero.
        /// </summary>
        public static string VALOR_DESPESA {
            get {
                return ResourceManager.GetString("VALOR_DESPESA", resourceCulture);
            }
        }
    }
}
